services:
  web:
    container_name: nagios
    image: ghcr.io/hkraal/docker-nagios@sha256:529ba285e121fc05c51c967a0358d9fdc6ac714e59fe80592912116f6a744c29
    restart: unless-stopped
    volumes:
      - var:/usr/local/nagios/var
      - etc:/usr/local/nagios/etc
    ports:
      - 8000:80
    environment:
      - TZ=Europe/Amsterdam
volumes:
  var:
  etc:
