services:
  web:
    container_name: nagios
    image: ghcr.io/hkraal/docker-nagios@sha256:c69c0ef86d8e2de9951d5982badb0029052bc75b224f775a2b48f2a64875fca6
    restart: unless-stopped
    volumes:
      - var:/usr/local/nagios/var
      - etc:/usr/local/nagios/etc
    ports:
      - 8000:80
    environment:
      - TZ=Europe/Amsterdam
volumes:
  var:
  etc:
