services:
  web:
    container_name: nagios
    image: ghcr.io/hkraal/docker-nagios@sha256:effeae14e2b2acf611a3128ea3ba5e1af1d0ffd96bf482cd41beab28deba0fa4
    restart: unless-stopped
    volumes:
      - var:/usr/local/nagios/var
      - etc:/usr/local/nagios/etc
    ports:
      - 8000:80
    environment:
      - TZ=Europe/Amsterdam
volumes:
  var:
  etc:
