services:
  web:
    container_name: nagios
    image: ghcr.io/hkraal/docker-nagios@sha256:33408e229e52e9271db0cb8041f009a4f66831042ec6325ddacf8e08ff5fe75b
    restart: unless-stopped
    volumes:
      - var:/usr/local/nagios/var
      - etc:/usr/local/nagios/etc
    ports:
      - 8000:80
    environment:
      - TZ=Europe/Amsterdam
volumes:
  var:
  etc:
